# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import time_pb2 as time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64\x62.proto\x12\x08iris_bil\x1a\ntime.proto\",\n\nDatabaseId\x12\x0c\n\x04ulid\x18\x01 \x01(\t\x12\x10\n\x08lookupId\x18\x02 \x01(\x05\"g\n\rDataUnitValue\x12\x11\n\x07str_val\x18\x01 \x01(\tH\x00\x12\x11\n\x07int_val\x18\x02 \x01(\x05H\x00\x12\x13\n\tfloat_val\x18\x03 \x01(\x02H\x00\x12\x14\n\nstring_val\x18\x04 \x01(\tH\x00\x42\x05\n\x03val\"\xa0\x01\n\tTelemItem\x12\"\n\x04\x64\x62id\x18\x01 \x01(\x0b\x32\x14.iris_bil.DatabaseId\x12\x14\n\x0c\x63hannel_name\x18\x02 \x01(\t\x12$\n\x03val\x18\x03 \x01(\x0b\x32\x17.iris_bil.DataUnitValue\x12\x33\n\ntimestamps\x18\x04 \x03(\x0b\x32\x1f.iris_bil.IrisDownlinkTimestamp\">\n\x08\x45ventArg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x03val\x18\x02 \x01(\x0b\x32\x17.iris_bil.DataUnitValue\"\x96\x01\n\x05\x45vent\x12\"\n\x04\x64\x62id\x18\x01 \x01(\x0b\x32\x14.iris_bil.DatabaseId\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12 \n\x04\x61rgs\x18\x03 \x03(\x0b\x32\x12.iris_bil.EventArg\x12\x33\n\ntimestamps\x18\x04 \x03(\x0b\x32\x1f.iris_bil.IrisDownlinkTimestamp\"@\n\nCommandArg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x03val\x18\x02 \x01(\x0b\x32\x17.iris_bil.DataUnitValue\"\xee\x01\n\x07\x43ommand\x12\x0c\n\x04ulid\x18\x01 \x01(\t\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.iris_bil.Command.CommandType\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\"\n\x04\x61rgs\x18\x04 \x03(\x0b\x32\x14.iris_bil.CommandArg\x12\x31\n\ntimestamps\x18\x05 \x03(\x0b\x32\x1d.iris_bil.IrisUplinkTimestamp\"C\n\x0b\x43ommandType\x12\x0f\n\x0b\x46SW_COMMAND\x10\x00\x12\x10\n\x0cMETA_COMMAND\x10\x01\x12\x11\n\rALIAS_COMMAND\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATABASEID._serialized_start=34
  _DATABASEID._serialized_end=78
  _DATAUNITVALUE._serialized_start=80
  _DATAUNITVALUE._serialized_end=183
  _TELEMITEM._serialized_start=186
  _TELEMITEM._serialized_end=346
  _EVENTARG._serialized_start=348
  _EVENTARG._serialized_end=410
  _EVENT._serialized_start=413
  _EVENT._serialized_end=563
  _COMMANDARG._serialized_start=565
  _COMMANDARG._serialized_end=629
  _COMMAND._serialized_start=632
  _COMMAND._serialized_end=870
  _COMMAND_COMMANDTYPE._serialized_start=803
  _COMMAND_COMMANDTYPE._serialized_end=870
# @@protoc_insertion_point(module_scope)
