# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntime.proto\x12\x08iris_bil\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x13IrisUplinkTimestamp\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.iris_bil.UplinkTimeType\"k\n\x15IrisDownlinkTimestamp\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.iris_bil.DownlinkTimeType*\xa9\x02\n\x0eUplinkTimeType\x12\x11\n\rULT_GENERATED\x10\x00\x12\x14\n\x10ULT_LOGGED_IN_DB\x10\n\x12\x11\n\rULT_OSIRIS_RX\x10\x14\x12\x11\n\rULT_OSIRIS_TX\x10\x19\x12\x10\n\x0cULT_YAMCS_RX\x10\x1e\x12\x10\n\x0cULT_YAMCS_TX\x10#\x12\x11\n\rULT_LANDER_RX\x10(\x12\x11\n\rULT_LANDER_TX\x10-\x12\x10\n\x0cULT_ROVER_RX\x10\x32\x12\x16\n\x12ULT_CMD_PROCESSING\x10<\x12\x13\n\x0fULT_CMD_WORKING\x10\x46\x12\x15\n\x11ULT_CMD_PROCESSED\x10P\x12\x14\n\x10ULT_CMD_EXECUTED\x10Z\x12\x12\n\x0eULT_CMD_FAILED\x10_*\x9e\x01\n\x10\x44ownlinkTimeType\x12\x11\n\rDLT_GENERATED\x10\x00\x12\x11\n\rDLT_LANDER_RX\x10\n\x12\x11\n\rDLT_LANDER_TX\x10\x0f\x12\x10\n\x0c\x44LT_YAMCS_RX\x10\x14\x12\x11\n\rDLT_OSIRIS_RX\x10\x1e\x12\x14\n\x10\x44LT_LOGGED_IN_DB\x10(\x12\x16\n\x12\x44LT_ARCHIVED_IN_DB\x10-b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPLINKTIMETYPE._serialized_start=272
  _UPLINKTIMETYPE._serialized_end=569
  _DOWNLINKTIMETYPE._serialized_start=572
  _DOWNLINKTIMETYPE._serialized_end=730
  _IRISUPLINKTIMESTAMP._serialized_start=57
  _IRISUPLINKTIMESTAMP._serialized_end=160
  _IRISDOWNLINKTIMESTAMP._serialized_start=162
  _IRISDOWNLINKTIMESTAMP._serialized_end=269
# @@protoc_insertion_point(module_scope)
