@startuml Iris FPrime WF121 RadioDriver Component Diagram

!theme crt-amber

skinparam DefaultTextAlignment left

left header
= <b>Iris FPrime WF121 RadioDriver Component Diagram</b>
* Shows which components fo the Wf121 RadioDriver are used by which other components.
* Hopefully gives a good idea of where to start if you're looking to understand this code and its delegation of responsibilities.


endheader

component RadioDriver
component "Wf121Serial::" as SerialInterface
component "Wf121UdpTxTask" as UdpTxTask
component "UdpTxTaskManager" as UdpTxTaskManager
component "Wf121RxTask" as RxTask
component "Wf121Parser::Mpsm" as Mpsm
component NetworkInterface
component "DirectMessage::DirectMessageDriver" as DirectMessageDriver
component "BgApi::BgApiDriver" as BgApiDriver

UdpTxTask =up=> RadioDriver
RxTask <=up=> RadioDriver
Mpsm =up=> RxTask
SerialInterface -up-> RadioDriver

NetworkInterface -right-> UdpTxTask

SerialInterface -up-> RxTask
SerialInterface -up-> UdpTxTask

NetworkInterface =up=> RadioDriver
DirectMessageDriver =up=> NetworkInterface
BgApiDriver =up=> NetworkInterface

UdpTxTaskManager =up=> NetworkInterface

BgApiDriver .right.> UdpTxTaskManager
BgApiDriver .right.> Mpsm
BgApiDriver .up.> UdpTxTask

left footer "\n\n\n* Bold arrow from 'A' to 'B' means **'A' is owned by (a member of) 'B'**\n* Arrow from 'A' to 'B' means **'A' is used by (called by) 'B'** \n* Dashed Arrow from 'A' to 'B' means **some part of 'A' is referenced by 'B'** (think pointer or simple struct use)"
@enduml