"""
Defines the Structure, Content, and Serialization for an IPC Message
containing a group of Payloads received in the downlink direction during a read
event.

Unlike `DownlinkedPacketsMessage`, these payloads may or may not have come
**directly** from a packet (they could have also come from a MetaChannel which
generated extra payloads based on what it's read from packet payloads).

Listen for `DownlinkedPacketsMessage` and read `packet.payloads` for each
`message.content.packets` if you want just payloads that came from packets.

@author: Connor W. Colombo (CMU)
@last-updated: 03/06/2023
"""
import attr

from IrisBackendv3.ipc.inter_process_message import IpmSubclassFactory, MessageContentAttrMixin
from IrisBackendv3.codec.payload_collection import EnhancedPayloadCollection


@attr.s(frozen=True, cmp=True, slots=True, auto_attribs=True)
class DownlinkedPayloadsContent(MessageContentAttrMixin):
    """
    Defines the Message Content wrapping a collection `Payloads` received from
    the downlink, either from a packet or generated by MetaChannels.

    Args:
        `payloads` (`EnhancedPayloadCollection`): The payloads.
    """
    payloads: EnhancedPayloadCollection


DownlinkedPayloadsMessage = IpmSubclassFactory(DownlinkedPayloadsContent)
