#Official Free RTOS distribution
#FREERTOS_ROOT_LOC = $(HOME)/workspace_v9/FreeRTOSv10.2.1/FreeRTOS
#FREERTOS_INCLUDES = $(FREERTOS_ROOT_LOC)/Source/include

#F-PRIME INCLUDES 
FPRIME_FREERTOS_INCLUDES = $(BUILD_ROOT)/Os/FreeRTOS
FPRIME_FREERTOS_STDTYPES_INCLUDES = $(BUILD_ROOT)/Fw/Types/Linux
