TI_ARM_COMPILER_ROOT_LOC = $(HOME)/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS
TI_ARM_LINKER_ROOT_LOC = $(TI_ARM_COMPILER_ROOT_LOC)
TI_ARM_ARCHIVER_ROOT_LOC = $(TI_ARM_COMPILER_ROOT_LOC)

TI_ARM_COMPILER_BIN_LOC = $(TI_ARM_COMPILER_ROOT_LOC)/bin/armcl
TI_ARM_COMPILER_INCLUDE_LOC = $(TI_ARM_COMPILER_ROOT_LOC)/include

TI_ARM_LINKER_BIN_LOC = $(TI_ARM_LINKER_ROOT_LOC)/bin/armcl
TI_ARM_LINKER_INCLUDE_LOC = $(TI_ARM_LINKER_ROOT_LOC)/include
TI_ARM_LINKER_LIB_LOC = $(TI_ARM_LINKER_ROOT_LOC)/lib

TI_ARM_ARCHIVER_BIN_LOC = $(TI_ARM_ARCHIVER_ROOT_LOC)/bin/armar