#ifndef BSP_H_
#define BSP_H_

void initializeGpios();

#define PWMA_H_CCR_REGISTER TIMER_B_CAPTURECOMPARE_REGISTER_6
#define PWMB_H_CCR_REGISTER TIMER_B_CAPTURECOMPARE_REGISTER_4
#define PWMC_H_CCR_REGISTER TIMER_B_CAPTURECOMPARE_REGISTER_2


#endif /* BSP_H_ */
