#ifndef BSP_H_
#define BSP_H_

void initializeGpios();

#define PWMA_H_CCR_REGISTER TIMER_B_CAPTURECOMPARE_REGISTER_6
#define PWMB_H_CCR_REGISTER TIMER_B_CAPTURECOMPARE_REGISTER_4
#define PWMC_H_CCR_REGISTER TIMER_B_CAPTURECOMPARE_REGISTER_2
#define ADC_CCR_REGISTER    TIMER_B_CAPTURECOMPARE_REGISTER_1

#define IPHASE_A_ADC_CHAN    ADC12_B_INPUT_A2
#define IPHASE_B_ADC_CHAN    ADC12_B_INPUT_A12
#define IPHASE_C_ADC_CHAN    ADC12_B_INPUT_A13


#endif /* BSP_H_ */
